### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by arjamizo** [whot/xf86-input-libinput#2]
Could you provide some informations what are possibilities and how can this be tested? 
I am extremly interested in this library due to problems with wheel-emulation on lenovo e540.

**Comment by whot** [comment]
closing this issue now, the readme was pushed ages ago, didn't realise this was still open.

fwiw, we use the fdo bugzilla, not github for issue tracking.

**Comment by arjamizo** [comment]
@kles4enko unfortunately I did not manage to do it. I do not remember why. I will try when I will be mobile with my laptop once again and it will be needed :) Thank you for remembering about me!
