### ISSUE TITLE
touch pad getting stuck in scrolling mode

### ISSUE THREAD

**Issue by AnAkIn1** [whot/xf86-input-libinput#4]
Hey,

I'm not sure where to report this, and even how to debug the issue, so I can't say for sure that the issue is with xf86-input-libinput, although this is what I use.

I am mostly using a mouse but the very rare times I try to use my touchpad, it is driving me crazy: basically, I think after trying to scroll with two fingers, the touchpad often get stuck in scrolling mode, it is impossible to move the cursor, unless I keep holding the touchpad and move my finger at the same time, or sometimes it also work again after I ALT-TAB.
I'm not sure if this is only related to scrolling, sometimes the cursor just get stuck, I'm trying everything to get it unstuck and nothing seem to work, although after holding the touchpad button multiple times, alt tabbing and doing all sort of things it usually end up working again.

Is there anything I can do to debug this issue?

I'm on Arch Linux, with the Plasma 5 DE. libinput 1.0 and xf86-input-libinput 0.14. I can't remember a time where I didn't have this issue, I think I've always had it (although I rarely use my touchpad).

**Comment by whot** [comment]
Please have a look at http://wayland.freedesktop.org/libinput/doc/latest/reporting_bugs.html, this repo is just a mirror for testing branches, the proper upstream is on freedesktop.org, with the bugzilla there.

**Comment by AnAkIn1** [comment]
Thanks, I've opened a bug report here:
https://bugs.freedesktop.org/show_bug.cgi?id=91875
