### ISSUE TITLE
two-finger scrolling with touchpad behaves oddly

### ISSUE THREAD

**Issue by philiparvidsson** [whot/xf86-input-libinput#6]
Description of the problem:

Two-finger scrolling is behaving oddly when combining vertical and horizontal scrolling.

How to reproduce:

Open a webpage, picture or text file (wide enough to allow for horizontal scrolling) and place two fingers on the touchpad. Move them in a circular fashion.

Expected behavior:

The webpage, picture or text should be moving around smoothly in a circle.

Actual behavior:

The webpage, picture or text jumps around and glitches, getting stuck on diagonal paths.

Hardware:

Asus ZenBook UX302LG

Software:

Ubuntu GNOME 16.10, libinput 0.19.0-1

**Comment by whot** [comment]
fwiw, this repo is just a mirror, please file bugs at https://bugs.freedesktop.org, under xorg component Input/libinput. Either way, pretty sure this was fixed a while ago, 0.19 is from last april. Please try to run the current releases first, thanks.
